Repository kivy/kivy, pull requests merged in 2018-10, with the labels that each got.

#5952 Change order of CGL backend to prefer dynamic GL symbol loading
  kivy/graphics/cgl.pyx
Labels: graphics

#5958 Fix 5783 carousel looping
  kivy/uix/carousel.py
Labels: widgets

#5957 Fix matrix transformation for orthographic projection
  kivy/graphics/transformation.pyx
Labels: graphics

#5959 Issue 5945
  kivy/core/video/__init__.py
  kivy/uix/video.py
Labels: widgets

#5962 Pango + fontconfig/freetype2 text provider
  .gitignore
  examples/text/pango_demo.py
  kivy/core/text/__init__.py
  kivy/core/text/_text_pango.pyx
  kivy/core/text/markup.py
  kivy/core/text/text_pango.py
  kivy/lib/kivy_endian.h
  kivy/lib/pango/freetype2.h
  kivy/lib/pango/pangoft2.pxi
  kivy/uix/label.py
  kivy/uix/textinput.py
  setup.py
Labels: core, feature, platform-linux, py3

#5961 ColorPicker refactor to prevent multiples event firing
  kivy/data/style.kv
  kivy/uix/colorpicker.py
Labels: widgets

#5966 Update with Cython 0.28.5
  setup.py
Labels: core

#5983 Issue #5773: Ensure to dispatch on_transform_with_touch event when the angle change
  kivy/uix/scatter.py
Labels: easy, widgets
