Repository kivy/kivy, pull requests merged in 2020-12, with the labels that each got.

#7250 Changelog: Fix script to use GitHub CLI for release notes and add 2.0.0 release notes
  doc/sources/changelog.rst
  kivy/tools/changelog_parser.py
Labels: Component: Misc

#7010 Doc: Warn that decorated methods might not be bindable.
  kivy/_event.pyx
Labels: Component: documentation

#7204 Kivy: print kivy's version even when not a release.
  kivy/__init__.py
Labels: Component: Misc

#7213 ScrollView: Match scroll effect stop condition to start condition.
  kivy/uix/scrollview.py
Labels: Component: Widgets

#7228 Image: Fix PIL label rendering shadow
  kivy/core/text/text_pil.py
Labels: Component: core-providers

#4854 Graphics: Add Sdl2 vsync
  kivy/config.py
  kivy/core/window/_window_sdl2.pyx
Labels: Component: graphics

#7257 Setup: Fix buggy detection of cython module name
  .ci/osx_ci.sh
  .ci/ubuntu_ci.sh
  .ci/windows_ci.ps1
  setup.cfg
  setup.py
Labels: Component: distribution

#7261 Camera: Revert "Fixes crash during camera configuration"
  kivy/uix/camera.py
Labels: Component: Widgets

#7209 Animation: Allow canceling all animated widgets
  kivy/animation.py
  kivy/tests/test_animations.py
Labels: Component: core-widget

#7263 Camera: Added API to change avfoundation camera provider orientation
  kivy/core/camera/camera_avfoundation.pyx
  kivy/core/camera/camera_avfoundation_implem.h
  kivy/core/camera/camera_avfoundation_implem.m
Labels: Component: core-providers

#7245 Resources: Add a cache for resource_find
  kivy/lang/builder.py
  kivy/resources.py
  kivy/tests/test_resources.py
Labels: Component: core-app

#7262 RecycleGridLayout : Fix layout when number of widgets match number of columns
  kivy/tests/test_uix_gridlayout.py
  kivy/tests/test_uix_recyclegridlayout.py
  kivy/uix/recyclegridlayout.py
Labels: Component: Widgets

#7277 SVG: Fix SVG instruction iteration for python 3.9.
  kivy/graphics/svg.pyx
Labels: Component: graphics

#7279 Window: prevent "empty" mousewheel events from breaking scrollview
  kivy/core/window/_window_sdl2.pyx
Labels: Component: core-providers

#7288 Documentation: Updated prerequisites and supported python version for iOS
  doc/sources/faq.rst
  doc/sources/guide/packaging-ios-prerequisites.rst
  doc/sources/guide/packaging-ios.rst
Labels: Component: documentation

#7271 Inspector: Prevent circular import breaking Window
  kivy/factory_registers.py
  kivy/modules/inspector.py
  kivy/tests/test_module_inspector.py
Labels: Component: Misc

#7264 Camera: Change play default to False
  kivy/uix/camera.py
Labels: Component: Widgets, Notes: API-break

#7286 Doc: Add negative size warning
  kivy/uix/widget.py
Labels: Component: documentation

#7290 Camera: improve avfoundation by using memoryview and re-scheduling the interval on framerate change
  kivy/core/camera/camera_avfoundation.pyx
  kivy/core/camera/camera_avfoundation_implem.h
  kivy/core/camera/camera_avfoundation_implem.m
Labels: Component: core-providers
