Repository kivy/kivy, pull requests merged in 2020-11, with the labels that each got.

#7195 Inlcude doc in PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Component: distribution

#7196 ScrollView: fix jumping to bottom when using scrollwheel.
  kivy/uix/scrollview.py
Labels: Component: Widgets, Priority: Critical

#7201 CI: Test all wheel versions, not just one per OS
  .ci/osx_ci.sh
  .ci/windows_ci.ps1
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/windows_wheels.yml
Labels: Component: tests/CI

#7203 Tests: Ensure Bubble uses it's superclass's valid private API
  kivy/tests/test_uix_bubble.py
Labels: Component: tests/CI

#7222 Docs: minor typo fix in layout docs
  doc/sources/gettingstarted/layouts.rst
Labels: Component: documentation

#7240 Docs: Re-write install docs.
  doc/sources/conf.py
  doc/sources/gettingstarted/installation.rst
  doc/sources/guide/basic.rst
  doc/sources/guide/packaging-osx.rst
  doc/sources/guide/packaging-windows.rst
  doc/sources/installation/deps-cython.rst
  doc/sources/installation/installation-android.rst
  doc/sources/installation/installation-devel.rst
  doc/sources/installation/installation-linux-venvs.rst
  doc/sources/installation/installation-linux.rst
  doc/sources/installation/installation-osx.rst
  doc/sources/installation/installation-rpi.rst
  doc/sources/installation/installation-windows.rst
  setup.cfg
Labels: Component: documentation

#7241 Docs: Add changelog to docs
  doc/sources/changelog.rst
  doc/sources/conf.py
  doc/sources/contents.rst.inc
  doc/sources/gettingstarted/installation.rst
  doc/sources/images/IOS_wordmark_(2017).svg
  doc/sources/images/conda.png
Labels: Component: documentation
