Repository kivy/kivy, pull requests merged in 2021-12, with the labels that each got.

#7691 MotionEvent: Fix keeping of the previous normalized position
  kivy/base.py
  kivy/input/motionevent.py
Labels: Component: input

#7679 MotionEvent: Fix calculation of z values in scale_for_screen method
  kivy/input/motionevent.py
Labels: Component: input

#7714 MouseMotionEventProvider: Update simulated touch graphics on window resize or rotate
  kivy/input/providers/mouse.py
Labels: Component: input

#7701 deprecate 'kivy.utils.SafeList'
  kivy/utils.py
Labels: Component: Misc, Notes: API-deprecation

#7717 MotionEvent: Fix docstring in dispatch_done method to reference post_dispatch_input
  kivy/input/motionevent.py
Labels: Component: documentation

#7641 Textinput: Fixes issues #7165, #7236, #7235
  kivy/uix/textinput.py
Labels: Component: Widgets, awaiting-reply

#7684 Enable pressure for touches in android (and ios?)
  examples/demo/touchtracer/main.py
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_sdl2.py
Labels: Platform: Android, Component: input
