Repository kivy/kivy, pull requests merged in 2021-03, with the labels that each got.

#7391 Added TouchRippleBehavior and TouchRippleButtonBehavior to factory_registers.py module
  kivy/factory_registers.py
Labels: Component: Widgets

#7390 Fix SoundAndroidPlayer state persisting after playback completion
  kivy/core/audio/audio_android.py
Labels: Component: core-providers, Platform: Android

#7389 Mouse: Fix mouse being offset by 2 pixels vertically
  kivy/core/window/window_sdl2.py
Labels: Component: core-providers

#7392 Docs: Fix packaging-osx docs (homebrew)
  doc/sources/guide/packaging-osx.rst
Labels: Component: documentation

#7403 Exceptions: Fix typos in message
  kivy/core/image/__init__.py
  kivy/input/providers/probesysfs.py
  kivy/input/recorder.py
Labels: Component: Misc

#7409 Window: Fix logging message
  kivy/core/window/_window_sdl2.pyx
Labels: Component: core-providers

#7426 Dropdown: Ensure visibility on reposition
  kivy/uix/dropdown.py
Labels: Component: Widgets

#7434 ModalView: code cleanup regarding detection of main-Window:
  kivy/tests/test_uix_modal.py
  kivy/uix/modalview.py
Labels: Component: Widgets

#7435 Docs: check for "sphinx" in command line
  kivy/__init__.py
Labels: Component: documentation

#7429 Clock: Print remaining events before next frame upon too much iteration error
  kivy/_clock.pxd
  kivy/_clock.pyx
Labels: Component: core-app

#7424 Properties: Speed up bare widget creation (3X) and property dispatching/setting
  kivy/_event.pxd
  kivy/_event.pyx
  kivy/properties.pxd
  kivy/properties.pyx
  kivy/tests/test_benchmark.py
  kivy/tests/test_knspace.py
  kivy/tests/test_properties.py
  kivy/uix/widget.py
Labels: Component: core-widget

#7437 TextInput: Remove broken and confusing `suggestion_text` property
  kivy/uix/textinput.py
Labels: Component: Widgets, Notes: API-break

#7439 Properties: Drop long number type and document numpy issues with NumericProperty
  kivy/properties.pyx
Labels: Component: core-widget

#7425 Mouse: Fix computation of relative touch position in MouseMotionEventProvider
  kivy/input/motionevent.py
  kivy/input/providers/mouse.py
  kivy/tests/async_common.py
  kivy/tests/common.py
  kivy/tests/test_app.py
  kivy/tests/test_mouse_multitouchsim.py
Labels: Component: input

#7442 EventDispatcher: Removed/replaced all basestring occurrences with str
  kivy/_event.pyx
Labels: Component: core-widget

#7441 Docs: Fix creating of docs of compoundselection.py
  kivy/uix/behaviors/compoundselection.py
Labels: Component: documentation

#7451 Docs: Fix Type Error when creating bytes from array in Python 3
  kivy/graphics/texture.pyx
Labels: Component: documentation

#7455 Graphics: Only check for threading issues once graphics is initialized
  kivy/graphics/instructions.pyx
Labels: Component: graphics
