Repository kivy/kivy, pull requests merged in 2021-02, with the labels that each got.

#7358 Doc: Fix doc code formatting
  kivy/graphics/instructions.pyx
Labels: Component: documentation

#7356 Widget: Widget.clear_widgets empty widget list does not remove all children
  kivy/tests/test_widget.py
  kivy/uix/widget.py
Labels: Component: core-widget, Notes: API-break

#7362 Build: No oneliners in [options.extras_require]
  setup.cfg
Labels: Component: distribution

#6290 Widget: Fix signature of add/remove/clear_widget to be consistent with base class
  examples/canvas/fbo_canvas.py
  examples/demo/showcase/main.py
  examples/shader/shadertree.py
  examples/widgets/fbowidget.py
  kivy/uix/accordion.py
  kivy/uix/actionbar.py
  kivy/uix/behaviors/compoundselection.py
  kivy/uix/boxlayout.py
  kivy/uix/bubble.py
  kivy/uix/carousel.py
  kivy/uix/dropdown.py
  kivy/uix/effectwidget.py
  kivy/uix/filechooser.py
  kivy/uix/floatlayout.py
  kivy/uix/layout.py
  kivy/uix/popup.py
  kivy/uix/recycleview/__init__.py
  kivy/uix/sandbox.py
  kivy/uix/scatterlayout.py
  kivy/uix/screenmanager.py
  kivy/uix/scrollview.py
  kivy/uix/settings.py
  kivy/uix/splitter.py
  kivy/uix/tabbedpanel.py
Labels: Component: core-widget, Notes: API-break

#7371 KV: Allow using f-strings in KV-lang
  kivy/lang/__init__.py
  kivy/lang/parser.py
  kivy/tests/test_lang.py
Labels: Component: KV-lang, Notes: Release-highlight

#7353 RecycleLayout: Allow setting x, y sizing of views independently
  kivy/uix/recyclelayout.py
Labels: Component: Widgets

#7372 Focus: Allow modifiers (e.g. numlock) be present to tab cycle focus
  kivy/uix/behaviors/focus.py
Labels: Component: Widgets

#7359 Fix first doc line being ignored
  kivy/graphics/instructions.pyx
Labels: Component: documentation

#7383 fix Dropdown reposition in scrollview/recycleview bug.
  kivy/uix/dropdown.py
Labels: Component: Widgets
