Repository kivy/kivy, pull requests merged in 2021-11, with the labels that each got.

#7688 Fix dds header comparison
  kivy/lib/ddsfile.py
Labels: Component: core-providers, Type: Bug

#7676 Bump support-request to v2. Previous integration has been shut down.
  .github/support.yml
  .github/workflows/support.yml
Labels: Component: tests/CI

#7703 [WIP] refactor kivy.lang
  kivy/lang/builder.py
  kivy/lang/parser.py
Labels: Component: KV-lang
