Repository kivy/kivy, pull requests merged in 2021-09, with the labels that each got.

#7612 Fixed unexpected overscrolling bug when using mouse wheel
  kivy/uix/textinput.py
Labels: Component: Widgets, Type: Bug

#7623 Sphinx: Use class instead of instance in add_lexer + Fixes search on sphinx>1.7.9
  doc/doc-requirements.txt
  doc/sources/.templates/layout.html
  doc/sources/sphinxext/preprocess.py
Labels: Component: documentation

#7624 Sphinx: Fixes missing documentation_options
  doc/sources/.templates/layout.html
Labels: Component: documentation

#7621 Fixed inconsistent behavior of TextInput bubble and handles
  kivy/uix/textinput.py
Labels: Component: Widgets

#7603 Fixes pong tutorial collision on the right side.
  examples/tutorials/pong/main.py
  examples/tutorials/pong/steps/step5/main.py
Labels: Component: documentation, Type: Documentation

#7605 PyInstaller hook: Replace modname_tkinter with 'tkinter'
  kivy/tools/packaging/pyinstaller_hooks/__init__.py
Labels: Component: Packaging

#7625 Update line number references in documentation
  doc/sources/guide/basic.rst
Labels: Component: documentation, Type: Documentation

#7637 Added Custom titlebar support
  examples/miscellaneous/custom_titlebar.py
  kivy/config.py
  kivy/core/window/__init__.py
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_sdl2.py
  kivy/input/providers/wm_common.py
  kivy/lib/sdl2.pxi
  kivy/tests/test_window_info.py
  kivy/tools/precommit_hooks/pre-commit-config.yaml
Labels: Component: core-providers, Notes: Release-highlight
