Repository kivy/kivy, pull requests merged in 2022-08, with the labels that each got.

#7943 Fixes some E275 - assert is a keyword. + other minor PEP8 fixes
  examples/widgets/sequenced_images/uix/custom_button.py
  kivy/atlas.py
  kivy/config.py
  kivy/core/camera/camera_android.py
  kivy/core/image/__init__.py
  kivy/core/text/__init__.py
  kivy/garden/__init__.py
  kivy/graphics/opengl.pyx
  kivy/graphics/vertex_instructions.pyx
  kivy/graphics/vertex_instructions_line.pxi
  kivy/input/recorder.py
  kivy/lang/builder.py
  kivy/lib/ddsfile.py
  kivy/network/urlrequest.py
  kivy/tests/test_uix_asyncimage.py
  kivy/uix/behaviors/button.py
  kivy/uix/behaviors/compoundselection.py
  kivy/uix/behaviors/touchripple.py
  kivy/uix/rst.py
  kivy/uix/screenmanager.py
  kivy/uix/textinput.py
  setup.cfg
Labels: Component: Misc

#7958 Use AddLevelName in kivy.Logger to define TRACE
  kivy/logger.py
  kivy/tests/test_logger.py
Labels: Component: core-app

#7916 Fixes NO DOCUMENTATION (module kivy.uix.recycleview)
  doc/autobuild.py
Labels: Component: documentation

#7946 Add doc for `Canvas.add()`
  kivy/graphics/instructions.pyx
Labels: Component: documentation

#7962 Refactored logging.ColoredFormatter to avoid deepcopy.
  kivy/logger.py
  kivy/tests/test_logger.py
Labels: Component: core-app

#7969 Config is not available when generating docs + Use `getdefault` instead of `has_option` + `get`
  kivy/network/urlrequest.py
Labels: Component: Misc

#7972 Fix trivial typo in workflow.
  .github/workflows/test_windows_python.yml
Labels: Component: tests/CI

#7973 Bump KIVY_CONFIG_VERSION and add a warning for future changes.
  kivy/config.py
Labels: Component: core-app

#7971 Support KivyLogMode environment variable for logging testing
  .ci/ubuntu_ci.sh
  .ci/windows_ci.ps1
  kivy/logger.py
  kivy/tests/pytest.ini
  kivy/tests/test_logger.py
Labels: Component: core-app

#7860 Ellipse: update angle_start, angle_end to explicit floats
  kivy/graphics/vertex_instructions.pyx
Labels: Component: graphics

#7975 Light clean up of stderr handling code.
  kivy/logger.py
  kivy/tests/test_logger.py
Labels: Component: core-app

#7985 Handle non-strings in logs.
  kivy/logger.py
  kivy/tests/test_logger.py
Labels: Component: core-app

#7979 #7978: Don't monkey-patch logging.root
  kivy/logger.py
  kivy/tests/test_logger.py
Labels: Component: core-app

#7974 Bump SDL2, SDL_image, SDL_mixer, SDL_ttf versions to latest stable release
  .ci/osx_ci.sh
  .ci/osx_versions.sh
  .ci/ubuntu_ci.sh
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
Labels: Component: distribution
