Repository kivy/kivy, pull requests merged in 2022-10, with the labels that each got.

#7989 Android Lifecycle convergence
  doc/sources/gettingstarted/installation.rst
  kivy/app.py
  kivy/core/window/__init__.py
  kivy/core/window/window_sdl2.py
Labels: Component: core-app

#7994 Use urlopen instead of build_opener when fetching files from 'internet'. Removes some PY2 compat.
  kivy/loader.py
Labels: Platform: Android, Platform: IOS, Component: core-app

#7999 Modify layout fix bug in how long text without space is cut
  kivy/core/text/text_layout.pyx
Labels: Component: core-providers

#8025 Release the GIL when performing SDL_GL_SwapWindow call.
  kivy/core/window/_window_sdl2.pyx
  kivy/lib/sdl2.pxi
Labels: Component: core-providers

#7847 Tests: ffpyplayer now ships cp310-* and Apple Silicon compatible wheels, so tests on the full version can be re-introduced.
  .github/workflows/test_osx_python.yml
Labels: Component: tests/CI

#8026 Typo : missing coma in the doc
  doc/sources/guide/packaging-windows.rst
Labels: Component: documentation

#8027 Typo : German Keyboard is QWERTZ
  kivy/data/keyboards/qwertz.json
Labels: Component: input

#8032 doc: Initial remarks on *BSD compatibility.
  doc/sources/gettingstarted/installation.rst
  doc/sources/gettingstarted/intro.rst
  doc/sources/guide/architecture.rst
  doc/sources/guide/basic.rst
  doc/sources/images/freebsd.png
  doc/sources/philosophy.rst
Labels: Component: documentation

#8039 Link to buildozer installation instructions instead of duplicating them
  doc/sources/guide/packaging-android.rst
Labels: Component: documentation

#8006 Use Platypus 5.4
  .ci/osx_ci.sh
Labels: Component: distribution

#8043 Bump SDL2 to `2.24.1` on Linux and macOS
  .ci/osx_ci.sh
  .ci/ubuntu_ci.sh
Labels: Component: distribution

#8041 installation-osx.rst: Minor code formatting
  doc/sources/installation/installation-osx.rst
Labels: Component: documentation
