Repository kivy/kivy, pull requests merged in 2022-03, with the labels that each got.

#7820 Patch gst current release to look for dlls in correct place for win store
  kivy/__init__.py
Labels: Notes: API-break, Component: distribution

#7826 add GitHub URL for PyPi
  setup.py
Labels: Component: documentation

#7830 EventManager: Fix typo in module doc
  kivy/eventmanager/__init__.py
Labels: Component: documentation

#7831 Changelog: Add 2.1.0 changelog
  doc/sources/changelog.rst
Labels: Component: Misc

#7835 Prepare 2.1.0 release
  kivy/_version.py
Labels: Component: distribution

#7837 Bump to 2.2.0.dev0
  kivy/_version.py
Labels: Component: distribution

#7854 Fixes 3.8.x pyenv install due to a recent change in clang [build wheel osx]
  .github/workflows/osx_wheels_app.yml
Labels: Component: tests/CI
