Repository kivy/kivy, pull requests merged in 2022-01, with the labels that each got.

#7678 Add support for Apple Silicon on CI/CD [build wheel osx] [build app osx]
  .ci/osx_ci.sh
  .ci/osx_versions.sh
  .ci/ubuntu_ci.sh
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
  doc/sources/installation/installation-osx.rst
Labels: Component: tests/CI

#7752 Improves docs on mobile, fixes duplicated getting started
  doc/sources/.static/fresh.css
  doc/sources/.static/kivy.js
  doc/sources/.templates/layout.html
  doc/sources/contents.rst.inc
Labels: Type: Documentation

#7493 GraphicUnitTest: Add clear_window_and_event_loop method
  kivy/tests/common.py
Labels: Component: tests/CI

#7726 Window.softinput_mode fix for "pan" and "below_target" modes when using kivy virtual keyboard.
  kivy/core/window/__init__.py
  kivy/input/motionevent.py
Labels: Component: core-providers

#7763 Removed Python3.6 from the supported ones, it reached EOL
  setup.cfg
  setup.py
Labels: Notes: API-break

#7760 Fixes benchmark tests on wheels
  .ci/ubuntu_ci.sh
  .ci/windows_ci.ps1
  .github/workflows/manylinux_wheels.yml
Labels: Component: tests/CI

#7770 WindowBase: Update bind list of properties: system_size, size, width, height and center
  kivy/core/window/__init__.py
Labels: Component: core-providers

#7771 Explain the '--' separator for option parsing.
  kivy/__init__.py
Labels: Component: core-app

#7774 Fix widget.disabled handling of value change of equal truthiness
  kivy/tests/test_widget.py
  kivy/uix/widget.py
Labels: Component: core-widget

#7773 Docs review before release 2.1.0
  doc/sources/.static/fresh.css
  doc/sources/conf.py
  doc/sources/contact.rst
  doc/sources/contribute.rst
  doc/sources/faq.rst
  doc/sources/gettingstarted/diving.rst
  doc/sources/gettingstarted/examples.rst
  doc/sources/gettingstarted/index.rst
  doc/sources/gettingstarted/installation.rst
  doc/sources/gettingstarted/intro.rst
  doc/sources/gettingstarted/properties.rst
  doc/sources/guide/android.rst
  doc/sources/guide/architecture.rst
  doc/sources/guide/basic.rst
  doc/sources/guide/config.rst
  doc/sources/guide/environment.rst
  doc/sources/guide/events.rst
  doc/sources/guide/lang.rst
  doc/sources/guide/licensing.rst
  doc/sources/guide/other-frameworks.rst
  doc/sources/guide/packaging-android.rst
  doc/sources/guide/packaging-ios-prerequisites.rst
  doc/sources/guide/packaging-ios.rst
  doc/sources/guide/packaging-osx.rst
  doc/sources/guide/packaging-windows.rst
  doc/sources/guide/packaging.rst
  doc/sources/guide/widgets.rst
  doc/sources/index.rst
  doc/sources/installation/installation-osx.rst
  doc/sources/installation/installation-windows.rst
  doc/sources/philosophy.rst
  doc/sources/tutorials/pong.rst
  kivy/tools/gallery.py
Labels: Component: documentation

#7744 Change default input_type to null. Add some warning regarding TYPE_TEXT_FLAG_NO_SUGGESTIONS
  kivy/core/window/__init__.py
  kivy/core/window/_window_sdl2.pyx
  kivy/uix/behaviors/focus.py
Labels: Component: core-providers, Notes: API-break

#7769 Add Linux AArch64 wheel build support
  .github/workflows/manylinux_wheels.yml
Labels: Component: distribution
