Repository kivy/kivy, pull requests merged in 2022-02, with the labels that each got.

#7658 Feature: EventManagerBase
  kivy/base.py
  kivy/core/window/__init__.py
  kivy/eventmanager/__init__.py
  kivy/input/motionevent.py
  kivy/input/providers/mouse.py
  kivy/uix/dropdown.py
  kivy/uix/modalview.py
  kivy/uix/relativelayout.py
  kivy/uix/sandbox.py
  kivy/uix/scatter.py
  kivy/uix/screenmanager.py
  kivy/uix/scrollview.py
  kivy/uix/widget.py
Labels: Component: core-widget

#7778 WindowBase: Don't return motion event in transform_motion_event_2d method
  kivy/core/window/__init__.py
Labels: Component: core-providers

#7785 Input providers: Assign type_id to MotionEvent subclasses
  kivy/core/window/window_sdl2.py
  kivy/input/providers/androidjoystick.py
  kivy/input/providers/hidinput.py
  kivy/input/providers/leapfinger.py
  kivy/input/providers/linuxwacom.py
  kivy/input/providers/mactouch.py
  kivy/input/providers/mtdev.py
  kivy/input/providers/tuio.py
  kivy/input/providers/wm_pen.py
  kivy/input/providers/wm_touch.py
  kivy/tests/common.py
  kivy/tests/test_uix_actionbar.py
  kivy/tests/test_uix_relativelayout.py
  kivy/tests/test_uix_slider.py
Labels: Component: input

#7786 WindowBase: Add on_drop_begin, on_droptext and on_drop_end events
  examples/miscellaneous/multiple_dropfile.py
  kivy/core/window/__init__.py
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_pygame.py
  kivy/core/window/window_sdl2.py
  kivy/lib/sdl2.pxi
Labels: Component: core-providers, Notes: API-deprecation

#7784 Linux AArch64 wheel build optimization
  .ci/ubuntu_ci.sh
  .github/workflows/manylinux_wheels.yml
Labels: Component: tests/CI

#7793 WindowBase|WindowSDL: Add drop position for all on_drop_xxx events
  kivy/core/window/__init__.py
  kivy/core/window/window_pygame.py
  kivy/core/window/window_sdl2.py
Labels: Component: core-providers

#7642 TextInput loading time optimisation for large texts
  kivy/uix/textinput.py
Labels: Component: core-widget, Notes: Release-highlight

#7795 WindowBase: Add *args to on_drop_xxx events
  kivy/core/window/__init__.py
Labels: Component: core-providers

#7796 EventManagerBase: Fix indentation and typos in the doc
  kivy/eventmanager/__init__.py
  kivy/uix/widget.py
Labels: Component: Widgets

#7794 Bring perf_test_textinput inline with changes in TextInput
  kivy/tests/perf_test_textinput.py
Labels: Component: tests/CI

#7804 Use the `KIVY_RPI_VERSION` env variable to force the build of `egl_rpi` in non Raspi CI builds
  doc/sources/installation/installation-rpi.rst
  setup.py
Labels: Component: distribution

#7775 Don't let 'ScrollEffect.reset()' set 'is_manual' to True
  kivy/effects/scroll.py
Labels: Component: Widgets

#7810 Track whether the clock has started
  kivy/_clock.pxd
  kivy/_clock.pyx
Labels: Component: core-app

#7807 Textinput: Simplified the swipe feature logic. Fixed a bug that was preventing to show the select all / paste bubble
  kivy/uix/textinput.py
Labels: Component: Widgets

#7814 :zap: Prevent crash (overflow error) when scrollbar is hidden
  kivy/uix/scrollview.py
Labels: Component: Widgets

#7815 MotionEvent: Fix indentation in module doc
  kivy/input/motionevent.py
Labels: Component: documentation

#7816 VideoPlayer: Defer before the next frame the default thumbnail and annotations loading
  kivy/tests/test_uix_videoplayer.py
  kivy/uix/videoplayer.py
Labels: Component: Widgets
