Repository kivy/kivy, pull requests merged in 2023-01, with the labels that each got.

#8088 Add support for sphinx `6.0.0`
  doc/sources/conf.py
Labels: Component: documentation

#8089 Add a warning about `keyboard_suggestions` usage on Android
  kivy/uix/behaviors/focus.py
Labels: Component: documentation

#8093 Add `gstreamer1.0-plugins-good` for `autoaudiosink` availability during tests
  .ci/ubuntu_ci.sh
Labels: Component: tests/CI

#8099 Install twine only when needed [build wheel]
  .ci/ubuntu_ci.sh
  .ci/windows_ci.ps1
Labels: Component: tests/CI

#8083 Allow changing `Window.fullscreen` and `Window.borderless` options after setup on iOS
  kivy/core/window/__init__.py
  kivy/core/window/_window_sdl2.pyx
Labels: Component: core-providers

#7632 Fixed enormously large cursor_x returned by get_cursor_from_xy when touch is righter then the last symbol of the line.
  kivy/uix/textinput.py
Labels: Component: Widgets, Notes: Release-highlight
