Repository kivy/kivy, pull requests merged in 2023-02, with the labels that each got.

#8117 Upgrade GitHub Actions
  .github/workflows/test_ubuntu_python.yml
Labels: Component: tests/CI

#8120 [build wheel] Upgrade more GitHub Actions
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/rpi_wheels.yml
  .github/workflows/test_osx_python.yml
  .github/workflows/test_windows_python.yml
  .github/workflows/windows_wheels.yml
Labels: Component: tests/CI

#8035 Simplify Animation._unregister
  kivy/animation.py
Labels: Component: core-widget

#8109 Fix for changes of Splitter.strip_cls having no effect
  kivy/uix/splitter.py
Labels: Component: Widgets

#8126 Switch back to `macos-latest` instead of `macos-11`
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
Labels: Component: tests/CI

#8129 Remove remaining nosetest settings in favor of pytest
  .gitignore
  Makefile
  kivy/__init__.py
  setup.cfg
Labels: Component: tests/CI

#8096 Introduce build script for SDL dependencies and `KIVY_DEPS_ROOT`
  .ci/Dockerfile.armv7l
  .ci/osx_ci.sh
  .ci/ubuntu_ci.sh
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
  .github/workflows/test_ubuntu_python.yml
  doc/sources/gettingstarted/installation.rst
  doc/sources/guide/environment.rst
  doc/sources/installation/installation-linux.rst
  doc/sources/installation/installation-osx.rst
  doc/sources/installation/installation-rpi.rst
  doc/sources/installation/installation-windows.rst
  setup.py
  tools/build_linux_dependencies.sh
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8139 Improve docs about `BoxShadow` behavior and usage.
  doc/sources/images/boxshadow_example_1.png
  doc/sources/images/boxshadow_example_2.png
  kivy/graphics/boxshadow.pyx
Labels: Component: documentation

#8076 New Feature: Always On Top
  kivy/config.py
  kivy/core/window/__init__.py
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_sdl2.py
  kivy/lib/sdl2.pxi
Labels: Component: core-providers

#8138 `BoxShadow`: Accept values for vertical and horizontal `spread_radius`
  doc/sources/images/boxshadow_spread_radius.svg
  doc/sources/images/boxshadow_spread_radius_inset.svg
  kivy/graphics/boxshadow.pxd
  kivy/graphics/boxshadow.pyx
  kivy/tests/test_graphics.py
Labels: Component: graphics

#7982 Use `SDL_WINDOWEVENT_DISPLAY_CHANGED` to notice about window switching display to update `_density` an `dpi`
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_sdl2.py
  kivy/lib/sdl2.pxi
Labels: Component: core-providers
