Repository kivy/kivy, pull requests merged in 2023-04, with the labels that each got.

#8142 New Feature: Allows to hide the taskbar icon
  kivy/config.py
  kivy/core/window/_window_sdl2.pyx
  kivy/lib/sdl2.pxi
Labels: Component: core-providers

#7925 Qwerty VKeyboard button fix( z, Q and W and ] ) on Linux(Ubuntu Focal Fossa)
  kivy/data/keyboards/qwerty.json
Labels: Component: Widgets

#7942 Config unicode support on Windows
  kivy/config.py
Labels: Component: core-app, Notes: Release-highlight

#8162 `Label`: allow different values of left, top, right and bottom for `padding`.
  kivy/core/text/__init__.py
  kivy/core/text/markup.py
  kivy/core/text/text_layout.pyx
  kivy/uix/label.py
Labels: Component: Widgets, Component: core-providers, Notes: Release-highlight

#8203 Migrate from `autotools` to `cmake` for SDL2 linux dependencies
  .ci/Dockerfile.armv7l
  .ci/ubuntu_ci.sh
  .github/workflows/manylinux_wheels.yml
  .github/workflows/test_ubuntu_python.yml
  doc/sources/installation/installation-linux.rst
  setup.py
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#8217 `Generate-sdist` needs `packaging` as a dependency [build wheel win]
  .ci/windows_ci.ps1
Labels: Component: tests/CI

#8191 XCode 14.3 fails to build SDL if `MACOSX_DEPLOYMENT_TARGET` < `10.13`
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#7852 Build python 3.9 wheels for RPi
  .ci/Dockerfile.armv7l
  .ci/ubuntu_ci.sh
  .github/workflows/rpi_wheels.yml
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#7846 Fix VKeyboard missing with custom keyboard class
  kivy/core/window/__init__.py
Labels: Component: core-providers
