Repository kivy/kivy, pull requests merged in 2023-07, with the labels that each got.

#8299 core-providers (audio): removes deprecated `filename` property
  kivy/core/audio/__init__.py
Labels: Component: core-providers, Notes: Release-highlight

#8303 Copy-edit to layouts.rst
  doc/sources/gettingstarted/layouts.rst
Labels: Component: documentation

#8310 pin `Pillow` version to `9.5.0`
  setup.cfg
Labels: Component: distribution

#8298 core-providers (audio): removes deprecated `status` property
  examples/audio/main.py
  kivy/core/audio/__init__.py
Labels: Component: core-providers, Notes: Release-highlight

#8315 Remove the extra position added to undo list while using Shift key
  kivy/uix/textinput.py
Labels: Component: Widgets, Platform: Android, Platform: OSX, Platform: IOS, Platform: Linux, Notes: Release-highlight

#8317 macOS dependencies: Build `libpng16` for `freetype`, so can render colored emoji
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
  doc/sources/installation/installation-osx.rst
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8313 Linux dependencies: Build `libpng16` for `freetype` so can render colored emoji
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#8300 core-providers (window): Removes deprecated `toggle_fullscreen` method
  kivy/core/window/__init__.py
  kivy/core/window/window_pygame.py
  kivy/core/window/window_sdl2.py
Labels: Component: core-providers, Notes: Release-highlight

#8323 Docs: Fix double word typos
  kivy/clock.py
  kivy/core/camera/__init__.py
  kivy/core/text/__init__.py
  kivy/core/window/__init__.py
  kivy/input/postproc/tripletap.py
  kivy/lang/__init__.py
  kivy/support.py
  kivy/uix/image.py
Labels: Component: documentation

#8324 Fix linux dependencies build instructions
  doc/sources/gettingstarted/installation.rst
Labels: Component: documentation
