Repository kivy/kivy, pull requests merged in 2023-08, with the labels that each got.

#8349 ObjectProperty: Fixed ValueError message in "convert" method.
  kivy/properties.pyx
Labels: Component: documentation

#8347 RecycleDataAdapter: Fixed typo in class docstring
  kivy/uix/recycleview/views.py
Labels: Component: documentation

#8359 Correct CI comment regarding logging tests
  .ci/windows_ci.ps1
Labels: Component: tests/CI

#8326 Add support for `Cython==3.x.x` and increase `cython_min` version
  kivy/core/image/_img_sdl2.pyx
  kivy/core/window/_window_sdl2.pyx
  kivy/lib/gstplayer/_gstplayer.pyx
  pyproject.toml
  setup.cfg
  setup.py
Labels: Component: distribution
