Repository kivy/kivy, pull requests merged in 2023-03, with the labels that each got.

#8157 Correct the flake8 pre-commit URL
  kivy/tools/precommit_hooks/pre-commit-config.yaml
Labels: Component: tests/CI

#8147 Detect High DPI on Linux Desktop
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_sdl2.py
  kivy/lib/sdl2.pxi
  kivy/metrics.py
  kivy/tests/test_properties.py
Labels: Component: graphics, Component: core-providers, Priority: High, SDL2, Platform: Linux, Notes: Release-highlight

#8156 Docs: Update the Ubuntu prerequisites to build Kivy and its dependencies
  doc/sources/installation/installation-linux.rst
Labels: Component: documentation

#8115 Use `font_direction` and `font_script_name` from SDL2_ttf
  examples/widgets/unicode_textinput.py
  kivy/core/text/__init__.py
  kivy/core/text/_text_sdl2.pyx
  kivy/lib/sdl2.pxi
  kivy/uix/label.py
Labels: Component: core-providers, SDL2, Notes: Release-highlight

#8146 Fix memory issue on iOS 16.2 for AVMetadataObject (during QRCode scan)
  kivy/core/camera/camera_avfoundation_implem.m
Labels: Component: core-providers

#8144 Added property for mouse draggable tab scrollbar to TabbedPanel
  kivy/uix/tabbedpanel.py
Labels: Component: Widgets, Type: Feature, Notes: Release-highlight

#7876 `Line`/`SmoothLine`: Fixes rendering issues related to corner radius and updates its order (`rounded_rectangle`) + add getter methods for `rounded_rectangle`, `rectangle`, `ellipse`, `circle`.
  kivy/graphics/vertex_instructions_line.pxi
  kivy/tests/test_graphics.py
Labels: Component: graphics, Notes: API-break, Notes: Release-highlight

#8164 `Ellipse`: Handle the number of segments and avoid division by zero
  kivy/graphics/vertex_instructions.pyx
Labels: Component: graphics

#8175 Update Copyright and LICENSE dates
  LICENSE
  doc/sources/index.rst
Labels: Component: documentation

#8174 Bump Linux dependencies versions on `tools/build_linux_dependencies.sh`
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#8173 Bump macOS dependencies versions on `tools/build_macos_dependencies.sh`
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8176 Bump Windows dependencies via `kivy_deps` packages
  pyproject.toml
  setup.cfg
Labels: Component: distribution

#8179 Update Python supported versions
  setup.cfg
  setup.py
Labels: Component: documentation

#8178 Bump `cython_max` version
  pyproject.toml
  setup.cfg
Labels: Component: distribution

#7626 New Feature: Allow control how many lines to scroll at once using the mouse wheel on TextInput
  kivy/tests/test_uix_textinput.py
  kivy/uix/textinput.py
Labels: Component: Widgets

#8170 Add svg rotation transform support
  examples/svg/rotated.svg
  kivy/graphics/svg.pyx
  kivy/tests/test_graphics_svg.py
Labels: Component: graphics

#8171 Make VideoFFPy work with RTSP streams.
  .gitignore
  kivy/core/video/video_ffpyplayer.py
Labels: Component: core-providers

#8070 Remove usage of `distutils` module which is deprecated and slated for removal in 3.12
  .ci/ubuntu_ci.sh
  kivy/tools/packaging/factory.py
  pyproject.toml
  setup.py
Labels: Component: distribution

#8183 Docs: Fixes a typo (issue #7838)
  kivy/uix/widget.py
Labels: Component: documentation

#8181 :book: Grammar tweaks to focus docstrings
  kivy/uix/behaviors/focus.py
Labels: Component: documentation

#8169 `Image`: add `fit_mode` feature
  kivy/data/style.kv
  kivy/uix/image.py
Labels: Component: Widgets, Notes: Release-highlight

#8163 `Line`/`SmoothLine`: `ellipse` - fix behavior and add feature to allow closing line through center of ellipse
  kivy/graphics/vertex_instructions_line.pxi
Labels: Component: graphics

#8058 Makes Windows DPI aware of scale changes
  kivy/core/window/__init__.py
  kivy/core/window/_window_sdl2.pyx
  kivy/core/window/window_sdl2.py
  kivy/lib/sdl2.pxi
Labels: Component: core-providers

#8187 `Line`/`SmoothLine` - `ellipse`: Handle the number of segments to match `Ellipse`
  kivy/graphics/vertex_instructions_line.pxi
Labels: Component: graphics
