Repository kivy/kivy, pull requests merged in 2023-12, with the labels that each got.

#8483 Check `$LastExitCode` after `pytest` run, so we can catch Windows fatal errors
  .ci/windows_ci.ps1
Labels: Component: tests/CI

#8490 `SetClipboardData` requires a memory object allocated with `GMEM_MOVEABLE` (and locks)
  kivy/core/clipboard/clipboard_winctypes.py
Labels: Component: core-providers

#8493 Correct `ActionBar` documentation
  kivy/uix/actionbar.py
Labels: Component: documentation

#8459 Deprecate `kivy.utils.interpolate` and improve related docs
  kivy/tests/test_utils.py
  kivy/utils.py
Labels: Component: Misc, Notes: API-deprecation

#8485 Refactor `filechoosertest_unicode.py`
  kivy/tests/test_filechooser_unicode.py
Labels: Component: tests/CI

#8501 Bump `kivy_deps.angle` version to `~=0.4.0`
  setup.cfg
Labels: Component: distribution

#8393 Add support for Python 3.12 (tests, wheels)
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
  .github/workflows/test_windows_python.yml
  .github/workflows/windows_wheels.yml
  setup.cfg
  setup.py
Labels: Component: distribution

#8505 Restrict the Pillow version to `>=9.5.0,<11`
  .ci/windows_ci.ps1
  doc/sources/gettingstarted/installation.rst
  setup.cfg
Labels: Component: distribution

#8513 Make sure build dependencies are installed for Kivy.app, and use default python version provided by `create-osx-bundle.sh`
  .ci/osx_ci.sh
  .github/workflows/osx_wheels_app.yml
Labels: Component: distribution

#8274 Add disclaimer to use `RecycleView` instead of `ScrollView` for large datasets
  kivy/uix/scrollview.py
Labels: Component: documentation

#8497 Added spanish layout json for the vkeyboard
  kivy/data/keyboards/es_ES.json
Labels: Component: core-widget, Component: input, Notes: Release-highlight

#8511 `PIL` text provider: Ensure consistent text height to prevent text from bouncing when typing
  kivy/core/text/text_pil.py
Labels: Component: core-providers

#8510 New feature: Add `limit_render_to_text_bbox` to `Label` to limit text rendering to the text bounding box, improving `Label` alignments.
  kivy/core/text/__init__.py
  kivy/core/text/text_pil.py
  kivy/uix/label.py
Labels: Component: core-providers

#8529 Request `--only-binary` for Pillow on Windows when testing wheels
  .ci/windows_ci.ps1
Labels: Component: tests/CI

#8533 Bump to `2.3.0rc1`
  kivy/_version.py
Labels: Component: distribution

#8535 Fix text attributes not changing after the settings panel is opened
  kivy/data/style.kv
  kivy/uix/settings.py
Labels: Component: Widgets

#8536 Bump to `2.3.0rc2`
  kivy/_version.py
Labels: Component: distribution

#8540 `PIL` text provider: Do not render text if font size is `< 1`
  kivy/core/text/text_pil.py
Labels: Component: core-providers
