Repository kivy/kivy, pull requests merged in 2023-11, with the labels that each got.

#8375 Fix use of `BoxShadow` with `canvas.add`, `canvas.insert` and `canvas.remove`
  kivy/graphics/boxshadow.pxd
  kivy/graphics/boxshadow.pyx
  kivy/tests/test_graphics.py
  setup.py
Labels: Component: graphics

#8218 Remove redundant `from kivy.base import EventLoop` import causing crashes in `window_sdl2`
  kivy/core/window/window_sdl2.py
Labels: Component: core-providers

#8428 Add `balenalib/raspberrypi3-debian-python:3.11-bookworm` to rpi builds for newer RPi OS
  .ci/Dockerfile.armv7l
  .github/workflows/rpi_wheels.yml
  doc/sources/gettingstarted/installation.rst
  doc/sources/installation/installation-rpi.rst
Labels: Component: Packaging

#8443 Slow down no-response bot
  .github/workflows/no-response.yml
Labels: Component: Misc

#8440 Fix #8438: SyntaxWarnings during doc generation.
  doc/sources/sphinxext/preprocess.py
Labels: Component: documentation

#8446 `Window.mouse_pos` is incorrect if the scale factor in Windows is not 100%.
  kivy/core/window/window_sdl2.py
Labels: Component: core-providers

#8447 Remove bountysource link, as bountysource looks died.
  README.md
Labels: Component: Misc

#8442 Edit Contact Us page in docs
  doc/sources/contact.rst
Labels: Component: documentation

#8464 Correct documentation of schedule_interval
  doc/sources/guide/events.rst
Labels: Component: documentation

#8453 Update support-requests action
  .github/workflows/support.yml
Labels: Component: Misc

#8435 Fixes markup `[sup]` followed by `[sub]` doesn't work (issue #8077)
  kivy/core/text/markup.py
Labels: Component: core-providers

#8448 Update Contribution Guidelines, add `FAQ`, `CONTACT` and `CONTRIBUTING` as separate documents, fix links
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  CONTACT.md
  CONTRIBUTING.md
  FAQ.md
  README.md
  doc/README.md
  doc/sources/changelog.rst
  doc/sources/contact.rst
  doc/sources/contribute-unittest.rst
  doc/sources/contribute.rst
  doc/sources/faq.rst
  doc/sources/gettingstarted/diving.rst
  doc/sources/gettingstarted/events.rst
  doc/sources/gettingstarted/installation.rst
  doc/sources/gettingstarted/intro.rst
  doc/sources/gettingstarted/rules.rst
  doc/sources/gsoc.rst
  doc/sources/gsoc2014.rst
  doc/sources/gsoc2015.rst
  doc/sources/gsoc2016.rst
  doc/sources/guide/android.rst
  doc/sources/guide/config.rst
  doc/sources/guide/inputs.rst
  doc/sources/guide/licensing.rst
  doc/sources/guide/packaging-android.rst
  doc/sources/guide/packaging-ios.rst
  doc/sources/guide/packaging-osx.rst
  doc/sources/guide/packaging-windows.rst
  doc/sources/index.rst
  doc/sources/installation/installation-osx.rst
  doc/sources/tutorials/firstwidget.rst
  setup.py
Labels: Component: documentation

#8206 Improved KV-lang parser error info when indentation is invalid
  kivy/lang/parser.py
  kivy/tests/test_lang.py
Labels: Component: KV-lang
