Repository kivy/kivy, pull requests merged in 2024-04, with the labels that each got.

#8673 Fix issue with `CompoundSelectionBehavior` silently ignoring `ValueError` in `on_selected_nodes` event
  kivy/uix/behaviors/compoundselection.py
Labels: Component: Widgets

#8545 Add example for `Smooth*` graphics instructions
  examples/canvas/antialiasing.py
Labels: Component: documentation

#8662 Graphics: Use indexed `GL_TRIANGLES` instead of `GL_TRIANGLE_FAN` to draw `Ellipse`
  kivy/graphics/vertex_instructions.pyx
Labels: Component: graphics

#8667 `Label`: Prevent overwriting `disabled_color` attribute when `color` is updated
  kivy/uix/label.py
Labels: Component: Widgets

#8680 Bump macOS ANGLE version to `chromium-6367_rev1`
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8681 Fix `ConfigParser.write` error with when `--save` is supplied as an argument
  kivy/__init__.py
Labels: Component: core-app

#8687 Update `cibuildwheel` pinned version to `2.17.0`
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
Labels: Component: distribution

#8682 Fix `xsel` import when clipboard is empty, and add timeout failsafe
  kivy/core/clipboard/clipboard_xsel.py
Labels: Component: core-providers

#8689 Pin build-time requirements versions, renovatebot will take care of the updates
  pyproject.toml
Labels: Component: distribution

#8207 Fix dropped motion events in mtdev provider.
  kivy/input/providers/mtdev.py
Labels: Component: input

#8690 Use PyPA `build` package to perform `bdist` and `kivy-examples`, to take advantage of build isolation
  .ci/Dockerfile.armv7l
  .ci/ubuntu_ci.sh
  .ci/windows_ci.ps1
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
  .github/workflows/test_ubuntu_python.yml
  .github/workflows/test_windows_python.yml
  .github/workflows/windows_wheels.yml
  Makefile
  doc/doc-requirements.txt
Labels: Component: distribution

#8694 `mock` gl backend egl context should not be managed by `sdl`
  kivy/core/window/_window_sdl2.pyx
Labels: Component: core-providers

#8677 Update `monitor` module to use `dp`
  kivy/modules/monitor.py
Labels: Component: core-app
