Repository kivy/kivy, pull requests merged in 2024-05, with the labels that each got.

#8711 Remove unused `sphinxcontrib-*diag` dependencies (and `funcparserlib`)
  doc/README.md
  doc/doc-requirements.txt
  setup.cfg
Labels: Component: documentation

#8713 Sunset `apple-silicon-m1` self-hosted runner, as now is supported by Github Hosted runners via `macos-latest` tag. Use `macos-13` for runs on Intel macs
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_osx_python.yml
Labels: Component: tests/CI

#8712 Make proper changes for `action/upload-artifact@v4` (wheels)
  .github/workflows/manylinux_wheels.yml
  .github/workflows/rpi_wheels.yml
  .github/workflows/windows_wheels.yml
Labels: Component: tests/CI

#8710 Ensure `benchmarks` artifact names are unique, as required by `actions/upload-artifacts@v4` [build wheel]
  .github/workflows/manylinux_wheels.yml
  .github/workflows/test_ubuntu_python.yml
  .github/workflows/test_windows_python.yml
  .github/workflows/windows_wheels.yml
Labels: Component: tests/CI

#8709 Sphinx/docs: Avoid usage of deprecated `style` keyword
  doc/sources/.templates/layout.html
Labels: Component: documentation

#8715 Make sure to pin a specific (or compatible) version of `sphinx` and related dependencies
  setup.cfg
Labels: Component: distribution

#8716 Use a `.ci/cicd-requirements.txt` file to handle CI/CD only dependencies
  .ci/cicd-requirements.txt
  .ci/ubuntu_ci.sh
  .ci/windows_ci.ps1
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_ubuntu_python.yml
  .github/workflows/windows_wheels.yml
Labels: Component: tests/CI

#8720 Install CI/CD deps also on `unit_test` job
  .github/workflows/test_ubuntu_python.yml
Labels: Component: tests/CI

#8724 Specify `MACOSX_DEPLOYMENT_TARGET=10.15` for all the self-built dependencies (except `ANGLE`)
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8741 `avplayer` audio provider: Fixes `seek` and `state` on iOS and macOS
  kivy/core/audio/audio_avplayer.py
Labels: Component: core-providers
