Repository kivy/kivy, pull requests merged in 2024-10, with the labels that each got.

#8836 Bump `SDL2` deps versions to latest available releases (macOS, Linux, Windows)
  pyproject.toml
  setup.cfg
  tools/build_linux_dependencies.sh
  tools/build_macos_dependencies.sh
Labels: Component: Packaging

#8847 Use coveralls Github Action instead of coveralls-python
  .ci/cicd-requirements.txt
  .github/workflows/test_ubuntu_python.yml
Labels: Component: tests/CI

#8853 Add docstring for `Instruction.flag_update`
  kivy/graphics/instructions.pyx
Labels: Component: graphics

#8868 [Backport devel-2.3.x] Specify `MACOSX_DEPLOYMENT_TARGET=10.15` for all the self-built dependencies
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8872 [Backport devel-2.3.x] Copy macOS frameworks via `cp -a` instead of `cp -r` to not mess up symbolic links
  tools/build_macos_dependencies.sh
Labels: Component: distribution
