Repository kivy/kivy, pull requests merged in 2024-11, with the labels that each got.

#8904 [Backport devel-2.3.x] Keep (or move) mandatory dependencies only in `install_requires`
  setup.cfg
Labels: Component: distribution

#8906 Update `CIBW_BUILD` environment variable to reflect supported Python versions
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
Labels: Component: tests/CI

#8913 Fix dependencies build for Raspberry Pi 32-bit OSes
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#8911 Revert #8415 and align `glShaderSource` `typedef` in `common_subset.h` with Khronos Headers
  kivy/graphics/cgl.pxd
  kivy/graphics/cgl_backend/cgl_debug.pyx
  kivy/graphics/cgl_backend/cgl_gl.pyx
  kivy/graphics/cgl_backend/cgl_mock.pyx
  kivy/include/common_subset.h
Labels: Component: graphics

#8792 Fix `SDL_EventFilter` definitions to match SDL definitions (fixes build on GCC 14)
  kivy/core/window/_window_sdl2.pyx
  kivy/lib/sdl2.pxi
Labels: Component: core-providers

#8910 fix: doc: highlight with python-console when needed
  kivy/lang/builder.py
  kivy/uix/widget.py
Labels: website

#8924 Fixes "permission denied" error on `macos-14` runner during osx app build job
  .ci/osx_ci.sh
Labels: Component: tests/CI

#8927 Bump version to `2.3.1.dev0`
  kivy/_version.py
Labels: Component: distribution

#8931 [Backport devel-2.3.x] Sphinx/docs: Avoid usage of deprecated `style` keyword
  doc/sources/.templates/layout.html
Labels: Component: documentation
