Repository kivy/kivy, pull requests merged in 2024-01, with the labels that each got.

#8542 Happy new year! Updated copyright year to 2024
  LICENSE
  doc/sources/conf.py
  doc/sources/index.rst
Labels: Component: documentation

#8543 Bump to `2.3.0rc3`
  kivy/_version.py
Labels: Component: distribution

#8551 Bump version to `2.3.0`
  kivy/_version.py
Labels: Component: distribution

#8554 Bump to `3.0.0.dev0` for development
  kivy/_version.py
Labels: Component: distribution

#8532 Updated ES vkeyboard layout to resemble a real ES keyboard layout
  kivy/data/keyboards/es_ES.json
Labels: Component: core-widget, Component: input, Notes: Release-highlight

#8594 Fix spelling on `unicode_textinput.py`
  examples/widgets/unicode_textinput.py
Labels: Component: documentation

#8587 Remove Python `3.7` from supported matrix and set minimum supported version to `3.8`
  .ci/Dockerfile.armv7l
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/rpi_wheels.yml
  .github/workflows/test_windows_python.yml
  .github/workflows/windows_wheels.yml
  doc/sources/gettingstarted/installation.rst
  doc/sources/installation/installation-rpi.rst
  setup.cfg
  setup.py
Labels: Component: distribution
