Repository kivy/kivy, pull requests merged in 2024-12, with the labels that each got.

#8935 Remove Python `3.8` from supported matrix and set minimum supported version to `3.9`
  .github/workflows/manylinux_wheels.yml
  .github/workflows/osx_wheels_app.yml
  .github/workflows/test_windows_python.yml
  .github/workflows/windows_wheels.yml
  setup.cfg
  setup.py
Labels: Component: distribution

#8936 Bump `ANGLE` version to `chromium-6778_rev1`
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8942 setup.cfg: The item `option.dependency_links` dropped by `pip` in 2019
  setup.cfg
Labels: Component: distribution

#8939 Fix a crash when loading a lot of images at once
  kivy/cache.py
Labels: Component: core-providers

#8945 Use `.items()` instead of extracting the dictionary value via explicit indexing
  kivy/__init__.py
  kivy/context.py
Labels: Component: Misc

#8946 Explicitely call `python3` in `build_linux_dependencies.sh`
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#8944 Python lint: Use `ruff` instead of `flake8`
  .ci/cicd-requirements.txt
  Makefile
  kivy/core/image/__init__.py
  kivy/core/window/__init__.py
  kivy/input/providers/mtdev.py
  kivy/lib/ddsfile.py
  kivy/lib/mtdev.py
  kivy/modules/_webdebugger.py
  kivy/network/urlrequest.py
  kivy/tools/image-testsuite/gimp28-testsuite.py
  kivy/tools/precommit_hooks/pre-commit-config.yaml
  kivy/tools/stub-gl-debug.py
  pyproject.toml
  setup.cfg
Labels: Component: tests/CI

#8961 Update version to 2.3.1rc1
  kivy/_version.py
Labels: Component: distribution

#8963 Update `CHANGELOG.rst` for `2.3.1` ad bump to `RELEASE` version
  doc/sources/changelog.rst
  kivy/_version.py
Labels: Component: distribution

#8965 Bump to `2.3.2.dev0` for development
  kivy/_version.py
Labels: Component: documentation

#8947 Replace legacy backticks with $( ) in linux dependencies build tool
  tools/build_linux_dependencies.sh
Labels: Component: distribution

#8967 Bump ANGLE version to `chromium-6778_rev2`
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8968 Add check (and add fallback) for `python3` cmd availability on linux dependencies build script
  tools/build_linux_dependencies.sh
Labels: Component: distribution
