Repository kivy/kivy, pull requests merged in 2025-02, with the labels that each got.

#8986 Refactor ScrollView
  kivy/effects/kinetic.py
  kivy/effects/scroll.py
  kivy/tests/test_effects.py
  kivy/uix/scrollview.py
Labels: Component: Widgets

#8987 Update README.md typo
  README.md
Labels: Component: documentation

#8991 Bump ANGLE version to `chromium-6943_rev1`
  tools/build_macos_dependencies.sh
Labels: Component: distribution

#8996 🐛 fix: KV Parser for f-strings now properly resolves nested attribute names
  kivy/lang/parser.py
  kivy/tests/test_lang.py
Labels: Component: KV-lang

#8995 Remove deprecated `play` property from `Video` and `VideoPlayer`
  doc/sources/migration.rst
  examples/cover/cover_video.py
  examples/kv/app_logo.kv
  examples/kv/app_video.kv
  kivy/tests/test_video.py
  kivy/uix/video.py
  kivy/uix/videoplayer.py
Labels: Component: Widgets, Notes: API-break

#8994 Remove deprecated `padding_x` and `padding_y` properties in `TextInput`
  doc/sources/migration.rst
  kivy/uix/textinput.py
Labels: Component: Widgets

#8993 Remove deprecated `file_encodings` property from `FileChooserController`
  doc/sources/migration.rst
  kivy/uix/filechooser.py
Labels: Component: Widgets
