Repository kivy/kivy, pull requests merged in 2025-01, with the labels that each got.

#8971 Happy new year! Updated copyright year to 2025
  LICENSE
  doc/sources/conf.py
  doc/sources/index.rst
Labels: Component: documentation

#8975 Fix highlight of TabbedPanelHeader when touch is released outside of the header(touch cancelled)
  kivy/uix/tabbedpanel.py
Labels: Component: Widgets, easy, Priority: Medium

#8980 Use new `ubuntu-22.04-arm` runner to build arm64 linux wheels
  .github/workflows/manylinux_wheels.yml
Labels: Component: tests/CI

#8977 Add `TouchRippleBehavior.ripple_pane` to its canvas when needed not during initialization
  kivy/uix/behaviors/touchripple.py
Labels: Component: Widgets

#8979 Fix the `AttributeError` that occurs when `TouchRippleButtonBehavior` is disabled.
  kivy/uix/behaviors/touchripple.py
Labels: Component: Widgets
